- hosts: localhost
  become: yes
  vars:
    dbuser: "psie"
    dbpass: "psie"
    dbname: "psie"
  tasks:
    - name: install git
      yum: name=git

    - name: install java
      yum: name=java

    - name: install python denendencies modules
      yum: name=gcc,gcc-c++,make,git,zlib-devel,sqlite-devel,sqlite,bzip2,bzip2-devel,readline-devel,openssl-devel

    - name: install psie web app dependencies modules
      yum: name=unzip

    # postgresql install
    - name: install postgresql
      yum: name={{ item }} state=latest
      with_items:
        - postgresql-server
        - postgresql-devel
        - postgresql-contrib
        - python-psycopg2
    - name: postgresql initdb
      shell: service postgresql initdb
    - name: start postgresql
      service: name=postgresql state=started enabled=yes
    - name: postgres user sudores
      lineinfile:
        dest: /etc/sudoers.d/postgres
        owner: root
        group: root
        mode: 0440
        line: "%vagrant ALL=(postgres) NOPASSWD: ALL"
        state: present
        create: yes
        validate: "visudo -cf %s"
    - name : create database
      postgresql_db:
        name: "{{ dbname }}"
        encoding: "UTF-8"
        login_user: postgres
      become_user: postgres
    - name: create user
      postgresql_user:
        db: "{{ dbname }}"
        name: "{{ dbuser }}"
        password: "{{ dbpass }}"
        priv: ALL
        state: present
        login_user: postgres
      become_user: postgres
    - name: update hba
      shell: sed -i -e 's/peer/trust/g' /var/lib/pgsql/data/pg_hba.conf
    - name: update hba
      shell: sed -i -e 's/ident/md5/g' /var/lib/pgsql/data/pg_hba.conf
    - name: restart postgres
      service: name=postgresql state=restarted
