# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define :mk do |c|
    c.vm.box = "centos/7"
    c.vm.hostname = "mk"
    c.vm.synced_folder ".", "/vagrant", disabled: false
    c.vm.network "private_network", ip: "192.168.33.110"
    c.vm.network :forwarded_port, host: 8080, guest: 8080
    c.vm.provider 'virtualbox' do |vm|
      vm.memory = 1024
    end
  end
end
